
#ifndef VTKDOUBLECONVERSION_EXPORT_H
#define VTKDOUBLECONVERSION_EXPORT_H

#ifdef DOUBLECONVERSION_STATIC_DEFINE
#  define VTKDOUBLECONVERSION_EXPORT
#  define DOUBLECONVERSION_NO_EXPORT
#else
#  ifndef VTKDOUBLECONVERSION_EXPORT
#    ifdef doubleconversion_EXPORTS
        /* We are building this library */
#      define VTKDOUBLECONVERSION_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKDOUBLECONVERSION_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef DOUBLECONVERSION_NO_EXPORT
#    define DOUBLECONVERSION_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef DOUBLECONVERSION_DEPRECATED
#  define DOUBLECONVERSION_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef DOUBLECONVERSION_DEPRECATED_EXPORT
#  define DOUBLECONVERSION_DEPRECATED_EXPORT VTKDOUBLECONVERSION_EXPORT DOUBLECONVERSION_DEPRECATED
#endif

#ifndef DOUBLECONVERSION_DEPRECATED_NO_EXPORT
#  define DOUBLECONVERSION_DEPRECATED_NO_EXPORT DOUBLECONVERSION_NO_EXPORT DOUBLECONVERSION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef DOUBLECONVERSION_NO_DEPRECATED
#    define DOUBLECONVERSION_NO_DEPRECATED
#  endif
#endif

#endif /* VTKDOUBLECONVERSION_EXPORT_H */
