# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget TKDraw TKTopTest TKViewerTest TKXSDRAW TKDCAF TKXDEDRAW TKTObjDRAW TKQADraw TKIVtkDraw)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target TKDraw
add_library(TKDraw SHARED IMPORTED)

set_target_properties(TKDraw PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKG2d;TKGeomBase;TKG3d;TKMath;TKBRep;TKGeomAlgo;TKTopAlgo;TKShHealing;TKMesh;TKService;TKHLR;/usr/lib/x86_64-linux-gnu/libtcl.so;/usr/lib/x86_64-linux-gnu/libtk.so;X11;Xext;Xmu;Xi"
)

# Create imported target TKTopTest
add_library(TKTopTest SHARED IMPORTED)

set_target_properties(TKTopTest PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKGeomAlgo;TKTopAlgo;TKernel;TKMath;TKBO;TKG2d;TKG3d;TKDraw;TKHLR;TKGeomBase;TKMesh;TKService;TKV3d;TKFillet;TKPrim;TKBool;TKOffset;TKFeat;TKShHealing"
)

# Create imported target TKViewerTest
add_library(TKViewerTest SHARED IMPORTED)

set_target_properties(TKViewerTest PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKGeomBase;TKFillet;TKBRep;TKTopAlgo;TKHLR;TKernel;TKMath;TKService;TKShHealing;TKBool;TKPrim;TKGeomAlgo;TKG2d;TKTopTest;TKG3d;TKOffset;TKMesh;TKV3d;TKDraw;TKOpenGl;/usr/lib/x86_64-linux-gnu/libtcl.so;/usr/lib/x86_64-linux-gnu/libtk.so;X11;Xext;Xmu;Xi;GL;/usr/lib/x86_64-linux-gnu/libfreetype.so"
)

# Create imported target TKXSDRAW
add_library(TKXSDRAW SHARED IMPORTED)

set_target_properties(TKXSDRAW PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKV3d;TKMath;TKernel;TKService;TKXSBase;TKMeshVS;TKG3d;TKViewerTest;TKG2d;TKSTEPBase;TKTopAlgo;TKGeomBase;TKGeomAlgo;TKMesh;TKDraw;TKSTEP;TKIGES;TKSTL;TKVRML;TKLCAF;TKDCAF;TKXCAF;TKRWMesh"
)

# Create imported target TKDCAF
add_library(TKDCAF SHARED IMPORTED)

set_target_properties(TKDCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKGeomBase;TKBRep;TKGeomAlgo;TKernel;TKMath;TKG2d;TKG3d;TKDraw;TKCDF;TKV3d;TKService;TKLCAF;TKFillet;TKTopAlgo;TKPrim;TKBool;TKBO;TKCAF;TKVCAF;TKViewerTest;TKStd;TKStdL;TKBin;TKBinL;TKXml;TKXmlL"
)

# Create imported target TKXDEDRAW
add_library(TKXDEDRAW SHARED IMPORTED)

set_target_properties(TKXDEDRAW PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKBRep;TKXCAF;TKernel;TKIGES;TKV3d;TKMath;TKService;TKXSBase;TKG2d;TKCAF;TKVCAF;TKDraw;TKTopAlgo;TKLCAF;TKG3d;TKSTEPBase;TKSTEP;TKMesh;TKXSDRAW;TKXDEIGES;TKXDESTEP;TKDCAF;TKViewerTest;TKBinXCAF;TKXmlXCAF;TKVRML"
)

# Create imported target TKTObjDRAW
add_library(TKTObjDRAW SHARED IMPORTED)

set_target_properties(TKTObjDRAW PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKCDF;TKLCAF;TKTObj;TKMath;TKDraw;TKDCAF;TKBinTObj;TKXmlTObj"
)

# Create imported target TKQADraw
add_library(TKQADraw SHARED IMPORTED)

set_target_properties(TKQADraw PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKService;TKG2d;TKDraw;TKV3d;TKGeomBase;TKG3d;TKViewerTest;TKCDF;TKDCAF;TKLCAF;TKFillet;TKTopAlgo;TKHLR;TKBool;TKGeomAlgo;TKPrim;TKBO;TKShHealing;TKOffset;TKFeat;TKCAF;TKVCAF;TKIGES;TKXSBase;TKMesh;TKXCAF;TKBinXCAF;TKSTEP;TKSTEPBase;TKXDESTEP;TKXSDRAW;TKSTL;TKXml;TKTObj;TKXmlL;TKBin;TKBinL;TKStd;TKStdL"
)

# Create imported target TKIVtkDraw
add_library(TKIVtkDraw SHARED IMPORTED)

set_target_properties(TKIVtkDraw PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKBRep;TKDraw;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKMath;TKMesh;TKService;TKTopAlgo;TKV3d;TKOpenGl;TKIVtk;VTK::IOImage;VTK::ImagingCore;VTK::InteractionStyle;VTK::RenderingOpenGL2;VTK::RenderingGL2PSOpenGL2;/usr/lib/x86_64-linux-gnu/libtcl.so;/usr/lib/x86_64-linux-gnu/libtk.so;X11;Xext;Xmu;Xi"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/OpenCASCADEDrawTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "TKernel" "TKG2d" "TKGeomBase" "TKG3d" "TKMath" "TKBRep" "TKGeomAlgo" "TKTopAlgo" "TKShHealing" "TKMesh" "TKService" "TKHLR" "TKBO" "TKV3d" "TKFillet" "TKPrim" "TKBool" "TKOffset" "TKFeat" "TKOpenGl" "TKXSBase" "TKMeshVS" "TKSTEPBase" "TKSTEP" "TKIGES" "TKSTL" "TKVRML" "TKLCAF" "TKXCAF" "TKRWMesh" "TKCDF" "TKCAF" "TKVCAF" "TKStd" "TKStdL" "TKBin" "TKBinL" "TKXml" "TKXmlL" "TKXDEIGES" "TKXDESTEP" "TKBinXCAF" "TKXmlXCAF" "TKTObj" "TKBinTObj" "TKXmlTObj" "TKIVtk" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
